#Planes client settings
[general_client]
	#Third person camera zoom on a plane
	# Default: 1.0
	# Range: 1.0 ~ 2.0
	plane_camera_distance_multiplier = 1.0
	#Third person camera zoom on a large plane
	# Default: 1.3
	# Range: 1.0 ~ 2.0
	large_plane_camera_distance_multiplier = 1.3
	#Third person camera zoom on a cargo plane
	# Default: 1.8
	# Range: 1.0 ~ 2.0
	cargo_plane_camera_distance_multiplier = 1.8
	#Third person camera zoom on a helicopter
	# Default: 1.2
	# Range: 1.0 ~ 2.0
	heli_camera_distance_multiplier = 1.2
